version: "3.8"

services:
  localstack:
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - SERVICES=sqs,sns,dynamodb
      - SQS_ENDPOINT_STRATEGY=off
      - LOCALSTACK_HOST=localstack:4566
      - DEBUG=${DEBUG:-0}
    volumes:
      - "./localstack:/etc/localstack/init/ready.d:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"

  db-pedido:
    image: postgres:15
    environment:
      - POSTGRES_DB=pedido_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  ms-pedido:
    build:
      context: ./fase5-ms-pedido
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - localstack
      - db-pedido
    environment:
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY=localstack
      - AWS_SECRET_KEY=localstack
      - AWS_SNS_ENDPOINT=http://localstack:4566
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-pedido:5432/pedido_db

  ms-pagamento:
    build:
      context: ./fase5-ms-pagamento
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - localstack
    environment:
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY=localstack
      - AWS_SECRET_KEY=localstack
      - AWS_DYNAMODB_ENDPOINT=http://localstack:4566
      - AWS_SNS_ENDPOINT=http://localstack:4566
      - AWS_SQS_ENDPOINT=http://localstack:4566
      - SERVER_PORT=8000